version: '3'

services:
  server:
    build:
      context: server
      dockerfile: ../Dockerfile
    command: npm start
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    depends_on:
      database:
        condition: service_healthy
    environment:
      PORT: ${SERVER_PORT}
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_NAME}
  
  client:
    build:
      context: client
      dockerfile: ../Dockerfile
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./client
        target: /usr/app
      - /usr/app/node_modules
    depends_on:
      - server
  
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: rowan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - database